
FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backapp.py .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "backapp:app"]
