name: Docker Build Test and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build Compose services
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for services
        run: sleep 20

      - name: Test backend home endpoint
        run: curl -f http://localhost:5000

      - name: Test backend database endpoint
        run: curl -f http://localhost:5000/db

      - name: Show running containers
        run: docker ps

      - name: Stop containers
        run: docker compose down

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image for Docker Hub
        if: github.event_name == 'push'
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend:latest ./backend

      - name: Push backend image to Docker Hub
        if: github.event_name == 'push'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend:latest
